# Generated by Django 2.0.2 on 2020-01-27 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('genre', models.CharField(choices=[('Pop', 'Pop'), ('Reggae', 'Reggae'), ('Rock', 'Rock')], default='Pop', max_length=25)),
                ('singer', models.CharField(max_length=50)),
                ('rating', models.PositiveIntegerField(default=1)),
            ],
        ),
    ]
